- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 'v0.4.2'
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
      files: '\.*$'
      exclude: '^vendor/'
    - id: trailing-whitespace
      files: '\.*$'
      exclude: '^vendor/'

- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
      args: ["-s"]
      exclude: '^vendor/'
    - id: go-lint
      exclude: '^vendor/'
    - id: go-vet
      exclude: '^vendor/'
    - id: validate-toml
    - id: no-go-testing
      files: 'integration-cli/.*\.go$'
      exclude: 'integration-cli/check_test\.go$'
