#!/bin/bash
set -ex

ROOT=/tmp/dockerdev
mkdir -p $ROOT

bundle=bundles/latest/binary-daemon
export PATH=$PWD/$bundle:$PATH

dockerd \
    --exec-root $ROOT \
    --graph $ROOT \
    --pidfile $ROOT/docker.pid \
    --experimental \
    --log-level debug \
    -H 0.0.0.0:3838
